### ISSUE TITLE
svgcontext: remove some attributes when possible

### ISSUE THREAD

**Issue by sug1no** [0xfe/vexflow#596]
svgcontext generates some additional attributes.

please refer to the following uri:
~~https://jsfiddle.net/jc5tut2f/~~

EDIT by @ronyeh: the example for version 3.0.9 is now here: https://jsfiddle.net/etko73nj/

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="500" height="500">
   <path stroke-width="1" fill="none" stroke="#999999" stroke-dasharray="none"
     font-family="Arial" font-size="10pt" font-weight="normal" font-style="normal"
     d="M10 80L410 80" />
...
   <rect stroke-width="0.3" fill="black" stroke="black" stroke-dasharray="none"
    font-family="Arial" font-size="10pt" font-weight="normal" font-style="normal"
    x="10" y="79.5" width="1" height="41" />
...
   <path stroke-width="0.3" fill="black" stroke="none" stroke-dasharray="none"
    font-family="Arial" font-size="10pt" font-weight="normal" font-style="normal"
    x="410" y="79.5" width="1" height="41" d="..." />
...
   <text stroke-width="0.3" fill="black" stroke="none" stroke-dasharray="none"
    font-family="Arial" font-size="12pt" font-weight="normal" font-style="normal"
    x="79.90079999999999" y="70"
    width="1" height="41">Render this</text>
...
</svg>
```

* the following attributes can be removed?:

- [x] {path, rect}.font-{family, weight, style, size} : #628
- [x] path.{x, y, width, height} : #628
- [x] text.{width, height} : #628

**Comment by gristow** [comment]
This is relatively low priority since it doesn't impact performance much, but I want to put some thoughts down while they're on my mind.

@sug1no your list of extra attributes is perfect.

They're not the only place we're adding attributes unnecessarily. Often we needlessly duplicate attributes already applied to a parent element. These are both a remnant of my (in retrospect) somewhat sloppy conversion of `CanvasContext` to `SVGContext`. It makes no difference in visual appearance, but if anyone is exporting and saving rendered SVG's (as I am...) it adds an awful lot of extra size. And if anyone is reaching into the DOM to grab and modify an SVG element, it means modifying all of that element's children as well.

I think the solution is to:
1) Rewrite `applyAttributes` to only apply those attributes that modify an element of that type (shape/path vs. text) as indicated in @sug1no's description.
2) Only apply an attribute to an element if that element's SVG parent (represented by the next level up on the stack) already has that attribute set.
3) Where possible, when a group is open, apply attributes to the group element instead of its children.

Each of these could be done in a separate PR to make this easier.

In the end, this will yield much cleaner SVG's, and make it far easier for users to grab an SVG element and style it with CSS, etc... Unless I'm mistaken, this won't create any breaking changes. Anyone who's already grabbing child elements to style elements manually will still be ok, as the children's attributes will be used.

I won't have time to get to this in the near future, so, consider any of this up for grabs!

**Comment by sug1no** [comment]
(1) is done by #628 .
But i won't have time to get to (2,3) ...

**Comment by ronyeh** [comment]
I updated the JSFiddle in the original comment to work with VexFlow 4:

https://jsfiddle.net/sg41xwz7/

**Comment by ronyeh** [comment]
https://jsfiddle.net/sg41xwz7/

There is still a bug in this example. When inspecting the SVG, there is a duplicate `<text>` element showing "Render this".

The bug is present in both 3.0.9 and 4.0.1.

**Comment by h-sug1no** [comment]
> there is a duplicate <text> element showing "Render this".

![image](https://user-images.githubusercontent.com/59550999/164368307-762257f6-3c85-40a4-bde4-efdeb9fbb523.png)

```js
const text = new TextNote({
    text: 'Render this',
...
voice.addTickables([text]);
...
// Render voice
voice.draw(context, stave);  // (1)
text.setContext(context).draw(); // (2)
```
- TextNode 'text' is rendered twice,  so the presence of two `<text>` elements is expected:
  - (1): by voice
  - (2): by 'text' itself
- (2) seems unnecessary... :  <https://jsfiddle.net/k5p2bnfz/>
- But, perhaps I was adding (2) because I wanted to check the DOM tree for multiple drawings

**Comment by rvilarl** [comment]
> (1) is done by #628 . But i won't have time to get to (2,3) ...

(2, 3) are included in #1457
